apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
  namespace: pprugger-dev
data:
  SERVER_URL: "http://127.0.0.1:3000"
  CLOUDANT_URL: "https://2ff22ba1-d0c9-41a3-8e92-96991af28c60-bluemix.cloudantnosqldb.appdomain.cloud"
  CLOUDANT_DB_NAME: "todo-db"
